### ISSUE TITLE
Drop GraphiQL in favor of already integrated playground?

### ISSUE THREAD

**Issue by tennox** [sysgears/create-apollo-app#70]
It seems to me GraphiQL is obsolete - https://www.prisma.io/blog/introducing-graphql-playground-f1e0a018f05d#how-is-this-different-compared-to-graphiql

Shouldn't we drop it from this boilerplate?

**Comment by larixer** [comment]
@TeNNoX How does your link confirm that GraphiQL is obsolete? Please clarify.

**Comment by tennox** [comment]
It doesn't **confirm** as in **guarantee** - but it basically is the case and it's also why its [integrated into apollo server](https://www.apollographql.com/docs/apollo-server/testing/graphql-playground/)

Here's a [list of additional features](https://github.com/prisma-labs/graphql-playground#how-is-this-different-from-graphiql)

**Comment by larixer** [comment]
@TeNNoX So, it is not obsolete. Graphql Playground has serious bugs:
https://github.com/prisma-labs/graphql-playground/issues/748
Despite the bug is closed, it was not really solved and results in bad user experience for some very basic need - authentication. GraphiQL doesn't have such problems and is known to be truly stable and working solution.

**Comment by tennox** [comment]
Alright. Seems I have incomplete knowledge. Thanks for considering, and in any case: Huge thanks for this tool :heart:
